/* Generated By:JavaCC: Do not edit this line. ELParserConstants.java */
package org.tonycox.ql.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ELParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int LIKE = 6;
  /** RegularExpression Id. */
  int NOTLIKE = 7;
  /** RegularExpression Id. */
  int LESSER = 8;
  /** RegularExpression Id. */
  int LESSER_OR_EQUALS = 9;
  /** RegularExpression Id. */
  int GREATER = 10;
  /** RegularExpression Id. */
  int GREATER_OR_EQUALS = 11;
  /** RegularExpression Id. */
  int IN = 12;
  /** RegularExpression Id. */
  int NOT_IN = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int RPAREN = 15;
  /** RegularExpression Id. */
  int EQUALS = 16;
  /** RegularExpression Id. */
  int NOTEQUAL = 17;
  /** RegularExpression Id. */
  int STRING = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"and\"",
    "\"or\"",
    "\"like\"",
    "\"!like\"",
    "\"lt\"",
    "\"lte\"",
    "\"gt\"",
    "\"gte\"",
    "\"in\"",
    "\"!in\"",
    "\"(\"",
    "\")\"",
    "\"eq\"",
    "\"!eq\"",
    "<STRING>",
  };

}
